### ISSUE TITLE
获取窗口名字需要去除空白符

### ISSUE THREAD

**Issue by FdolaLily** [CHNZYX/AutoPuling#3]
class_name = win32gui.GetClassName(hwnd).strip()
window_name = win32gui.GetWindowText(hwnd).strip()

需要改成这样，在我的电脑上测试获得的window_name是“无限暖暖 ”，最后有个空白符，导致一直捕获不到窗口

**Comment by CHNZYX** [comment]
ok，我就说哪里不对劲。我还以为之前那个pr测试过，大意了。。
